config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
  devise_for :members, :controllers => {registrations: 'registrations'} 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @member = current_member
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_member!, except: [:index, :show]
  # GET /posts or /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
    @member = current_member
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_member.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_member.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:post, :member_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params
    params.require(:member).permit(:name,:bio,:email,:password, :password_confirmation)
  end
  def account_update_params
    params.require(:member).permit(:name,:bio, :email,:password, :password_confirmation,:current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def resource_name
    :member
  end

  def resource
    @resource ||= Member.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:member]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="navbar pl-6 is-transparent is-spaced">
        <div class="navbar-brand">
          <%= link_to root_path, class:'title' do%>
           <h2 class="title">Members Only</h2>
          <%end%>
        </div>
        <div class="navbar-menu navbar-end pr-6">
          <% if member_signed_in? %>
          
            <%= link_to current_member.name, edit_member_registration_path, class: 'navbar-item ' %>
            
            
            <%= link_to "Log out", destroy_member_session_path, method: :delete, class: 'navbar-item' %>  
          <% else %>
              <%= link_to 'Sign up', new_member_registration_path, class: 'navbar-item' %>
          <% end %>
        </div>
      </div>





    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="columns">
  <div class="column is-8 is-offset-1">
    <div class="box">
      <div class="container">
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="field">
    <div class="control">
      <%= f.input :post, 
                  input_html: { class:"textarea"},
                  label_html: { class: "label"},
                  wrapper: false %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.button :submit, "Update post", class:"button is-success" %>
    </div>
  </div>

<% end %>

      </div>
    </div>
  </div>
</div>

app/views/posts/_new_post.html.erb
<div class="box">
  <div class="media">
    <div class="media-content">
      <%= simple_form_for(@post) do |f|%>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="field">
          <div class="control">
            <%= f.input :post,
                        wrapper:false,
                        autofocus: true,
                        label: "New Post",
                        label_html: { class:"label" },
                        input_html: { class:"textarea" },
                        placeholder: "Write a new post" %>
          </div>
        </div>
        <div class="field">
          <div class="control">
            <%= f.button :submit, 
                         "Post",
                         class:"button is-success" %>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<% if Post.first.nil? %>
  <h2 class="title">No posts yet.</h2>
<% else %>
  <% @posts.each do |post|%>
    <%= link_to post do %>
    <div class="container mb-4">
        <div class="box">
          <div class="media">
            <div class="media-left">
              <p class="image is-64x64">
                <img src="https://www.iconninja.com/files/507/766/417/avatar-ninja-face-figure-cat-icon.png" alt="This is a placeholder image.">
              </p>
            </div>
            <div class="media-content">
              <div class="content">
                <% if member_signed_in? %>
                <strong><%= post.member.name %></strong> <br />
                <%end%>
                <%= post.post %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <% if member_signed_in? && post.member.id == current_member.id%>
        <div class="level box has-background-light">
          <div class="level-item has-text-centered">  
            <%= link_to edit_post_path post do %>
              <span class="icon">
                <i class="fas fa-edit"></i>
              </span>
            <%end%>
          </div>
          <div class="level-item has-text-centered">
            <%= link_to root_path do %>
              <span class="icon">
                <i class="far fa-comments"></i>
              </span>
            <%end%>
          </div>
          <div class="level-item has-text-centered">
            <%= link_to post, method: :delete, data: {confirm:"Are you sure you want to delete the post?"} do %>
              <span class="icon">
                <i class="far fa-trash-alt"></i>
              </span>
            <%end%>
          </div>
        </div>
      <% elsif member_signed_in? && post.member.id != current_member.id %>
        <div class="level box has-background-light">
          <div class="level-item has-text-centered">
            <%= link_to root_path do %>
              <span class="icon">
                <i class="far fa-comments"></i>
              </span>
            <%end%>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>   
<% end %>

app/views/posts/_profile.html.erb
<div class="panel">
  <%= link_to edit_member_registration_path do%>
    <p class="panel-heading">Profile</p>
  
  <div class="panel-block">
    <div class="media">
      <div class="media-left">
        <p class="image is-64x64">
          <img src="https://bulma.io/images/placeholders/64x64.png" alt="This is a placeholder image.">
        </p>
      </div>
      <div class="media-content">
        <div class="content">
            <strong><%= member.name %></strong> <br />
            <small><%= member.bio %></small>
        </div>
      </div>
    </div>
  </div>
  <%end%>
  <div class="panel-block">
    <div class="level is-mobile">
      <div class="level-item">
        <div>
          <p class="heading">Posts</p>
          <p class="title is-6"><%= current_member.posts.count %></p>
        </div>
      </div>
      <div class="level-item ml-5">
        <div>
          <p class="heading">Comments</p>
          <p class="title is-6">$ph$</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_sign_in.html.erb
<div class="box">
  <div class="media">
  <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  
  <%= f.error_notification %>
    <div class="field">
      <div class="control">
        <%= f.input :email,
                    required: true,
                    wrapper: false,
                    autofocus: true,
                    input_html: { autocomplete: "email", class: 'input' },
                    label_html: { class: 'label'} %>
      </div>
    </div>
    <div class="field">
      <div class="control">
        <%= f.input :password,
                required: false,
                input_html: { autocomplete: "current-password", class:'input' },
                wrapper: false,
                label_html: { class: 'label'} %>
      </div>
    </div>
    <div class="field">
      <div class="control">
        <%= f.button :submit, "Sign in", class: 'button is-success ' %>
      </div>
    </div>
    <%= link_to "Forgot your password? Hope you didn't cause this isn't working yet.", new_password_path(resource_name) %>
  <% end %>
    </div>
</div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-three-quarters">
        <% if member_signed_in? %>
          <%= render 'new_post'%>
          <%= render 'post'  %>
        <%else%>
          <%= render 'post'%>
        <%end%>
      </div>
      <div class="column">
        <% if member_signed_in? %>
          <%= render 'profile', member: @member %>
        <%else%>
          <%= render 'sign_in'%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="columns">
  <div class="column is-9 is-offset-1"> 
    <div class="panel">
      <p class="panel-heading">
        <strong><%= @post.member.name %></strong>
      </p>
      <div class="panel-block">
        <p>
        <%= @post.post %>
        </p>
      </div>
      <div class="panel-block level">
        <%= link_to edit_post_path(@post), class:"level-item" do %> 
          <span class="icon">
            <i class="fas fa-edit"></i>
          </span>
        <%end%>
        <%= link_to post_path(@post),method: :delete,data: {confirm: "Are you sure you want to delete this post?"}, class:"level-item" do %> 
          <span class="icon">
            <i class="fas fa-trash-alt"></i>
          </span>
        <%end%>
      </div>
    </div>
  </div>
</div>